### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by Theetjuh** [humbertogontijo/homeassistant-roborock#427]
## Version of the custom_component
1.0.9

## What vacuum are you using?
Roborock S7

## Describe the bug
Since the update to 1.0.9 the integration isn't working anymore, with 1.0.8 it was still working but I got a map error which seemed to be a quite frequent issue.

I removed the integration, redownloaded and set it up a few times without any luck.

I am using the option 'cloud integration'.

## Debug log

```This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/roborock/__init__.py:125
Integration: Roborock (documentation, issues)
First occurred: 10:40:12 (3 occurrences)
Last logged: 13:22:36

Error setting up entry xxx@xxx.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 125, in async_setup_entry
    map_client.add_listener(lambda attr, _data: data_coordinator.update_device(attr, _data))
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RoborockMqttClient' object has no attribute 'add_listener'

```

**Comment by humbertogontijo** [comment]
Something is off. It looks like the roborock lib was not updated correctly

**Comment by Theetjuh** [comment]
After some waiting I could add the integration again, it accepted the username/password and got the same error again, went into the options and enabled cloud integration.

Still didn’t work, enabled debug logging and restarted HA again, exactly the same error as post 1

**Comment by Trebacz** [comment]
![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/19363347/3da3c22b-c545-4e44-aeb1-788eaf4d9dad)
I get an infinite spinner trying to update from 1.0.8 to 1.0.9. It's been like this a couple days. Does that help? My 1.0.8 version still "works". Scared to uninstall anything.

**Comment by Theetjuh** [comment]
I got no idea what to do now, even when I go back to older versions that definitely worked ... give the exact same error.

**Comment by humbertogontijo** [comment]
@Theetjuh the issue you are having is that your HA instance is not updating the python-roborock library for whatever reason

**Comment by Theetjuh** [comment]
I got no idea what the python-roborock library is, is that the integration from here or the default integration?

Is there something I can try?

**Comment by humbertogontijo** [comment]
The same thing you did before deleting the roborock folder, restarting, adding it again, restarting. Make sure to remove the integration from your config > devices and services before all

**Comment by Theetjuh** [comment]
I removed the integration, offcourse with the devices, else it doesn’t work.
I manually didn’t remove anything btw, just checked if the process did it.

So I did that all already, restarted a dozen times in between.

**Comment by nerdtechse** [comment]
I have the same problem as @Theetjuh.. @humbertogontijo is there a way to upgrade python-roborock library manualy?

**Comment by humbertogontijo** [comment]
Try to download main branch version instead of 1.0.9. That will probably trigger another download of the lib since it is using a newer version

**Comment by Theetjuh** [comment]
Thanks that fixed it for me.

**Comment by artem-zinnatullin** [comment]
Hm, can we reopen this issue?

I got the same stacktrace after Updating Roborock integration via HACS from 1.0.8 (I think) to 1.0.11 running HomeAssistant docker image 2023.8.4

```js
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 126, in async_setup_entry
    map_client.add_listener(data_coordinator.update_device)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RoborockMqttClient' object has no attribute 'add_listener'
```

1. I've tried "Redownload" through HACS and restart — same error
2. Not sure how to trigger re-download of `python-roborock` from reading this discussion :/
3. I'm sure many more people will hit the issue as they update HACS Roborock integration, would be great to find some fix that doesn't require user intervention
