### ISSUE TITLE
Failed to set up intergration

### ISSUE THREAD

**Issue by Dennisd80** [humbertogontijo/homeassistant-roborock#94]
After updating to the latest version (now 0.19) i am unable to set up this imtergration. I am getting the following error: `Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/roborock/__init__.py:30
Integration: Roborock (documentation, issues)
First occurred: 01:42:48 (1 occurrences)
Last logged: 01:42:48

Error setting up entry Roborock for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 81, in async_setup_entry
    translation = get_translation(hass)
  File "/config/custom_components/roborock/__init__.py", line 40, in get_translation
    translation = get_translation_file(
  File "/config/custom_components/roborock/__init__.py", line 30, in get_translation_file
    sensor = entity.get("sensor")
AttributeError: 'NoneType' object has no attribute 'get'
`

I tried downgrading to 0.17, removing an re adding the imtergration but all without any results. Running on Home Assistant 2022.12.9

**Comment by clipse2004** [comment]
Yep same here

**Comment by Trebacz** [comment]
I also got an error after upgrading from 0.17 to 0.19. I did "These new integration options are a breaking change. After updating the integration make sure to click the configure button under "Devices & Services" and save. Then reload the integration."

I stayed on 0.19, tried to reload the integrations (it did not succeed), and then I restarted HA. Everything came up after that.

I think I missed "Then reload the integration."  So I'm up and running on 0.19 after a second restart of HA.

**Comment by clipse2004** [comment]
> I also got an error after upgrading from 0.17 to 0.19. I did "These new integration options are a breaking change. After updating the integration make sure to click the configure button under "Devices & Services" and save. Then reload the integration."
> 
> I stayed on 0.19, tried to reload the integrations (it did not succeed), and then I restarted HA. Everything came up after that.
> 
> I think I missed "Then reload the integration." So I'm up and running on 0.19 after a second restart of HA.

Not working for me.ried the exact same thing, restarted the host myself, no chance. 
The integration won't load, am now back to 0.0.17.

**Comment by shred86** [comment]
It looks like the translation file is missing the keys for some of the new entries that were added. I just made a [PR](https://github.com/humbertogontijo/homeassistant-roborock/pull/97) to fix this but I just copied over the English translations for now with the expectation that someone who speaks the language can translate it.

**Comment by humbertogontijo** [comment]
I released v0.0.20 hoping to fix this problem for anyone who has it

**Comment by Dennisd80** [comment]
Fixed it for me 0.20 thanks

**Comment by clipse2004** [comment]
Yep for me too! 
thanks
