### ISSUE TITLE
This integration breaks with the latest HA (2023.10.x)

### ISSUE THREAD

**Issue by jimz011** [humbertogontijo/homeassistant-roborock#488]
Hi, I love this integration as the default integration lacks a lot of features (mainly the vacuum map).
Unfortunately the latest dev and beta versions break this component. I know it is still in beta, but I only mention it because I always run beta's and this is the first time we run into trouble with this component.

The error given is:
```
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

I tried reinstalling but unfortunately it remains the same.

**Comment by Lash-L** [comment]
There should be more in the error log, can you share?

**Comment by jimz011** [comment]
There were indeed, my bad.

These came up in the logs

```
Logger: homeassistant.config_entries
Source: config_entries.py:2069
First occurred: 12:39:47 AM (2 occurrences)
Last logged: 3:10:16 AM

Error occurred loading flow for integration roborock: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)
```

**Comment by Lash-L** [comment]
fixed in https://github.com/humbertogontijo/homeassistant-roborock/pull/489

Basically, the way we exclude the recorder entities from being logged for the camera is no longer supported. This is the new way to do it

**Comment by Lash-L** [comment]
Please redownload with main and see if your problems are resolved

**Comment by syndikatss** [comment]
> Please redownload with main and see if your problems are resolved

I installed the main version, but now there is a camera error
`Unexpected exception importing platform custom_components.roborock.camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/roborock/camera.py", line 84, in <module>
    class VacuumCameraMap(RoborockEntity, Camera):
  File "/config/custom_components/roborock/camera.py", line 116, in VacuumCameraMap
    ATTR_BATTERY_ICON,
    ^^^^^^^^^^^^^^^^^
NameError: name 'ATTR_BATTERY_ICON' is not defined`

and

`Unable to prepare setup for platform roborock.camera: Platform not found (Exception importing custom_components.roborock.camera).`

**Comment by jscherry** [comment]
Same error. Tried Version 1.0.6 to 1.0.11. Each give same config error as above.
Error occurred loading flow for integration roborock: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)

**Comment by Lash-L** [comment]
@syndikatss use a file editor to edit the camera.py file to have 
from homeassistant.components.vacuum import ATTR_BATTERY_ICON

**Comment by syndikatss** [comment]
> use a file editor to edit the camera.py file to have
> from homeassistant.components.vacuum import ATTR_BATTERY_ICON

To be honest, I didn’t really understand 😁

**Comment by tefracky** [comment]
> @syndikatss use a file editor to edit the camera.py file to have 
> from homeassistant.components.vacuum import ATTR_BATTERY_ICON

This seems to work.

**Comment by jimz011** [comment]
> @syndikatss use a file editor to edit the camera.py file to have 
> from homeassistant.components.vacuum import ATTR_BATTERY_ICON

Yup this seems to work, no more errors shown now, the map gets loaded again.

Thanks for this fix!

**Comment by Lash-L** [comment]
You can now pull main and it should work.

Sorry for the broken first fix! I don't have a environment setup for the custom component on my machine rn, just the core component, so I was doing it in the github editor

**Comment by wormiedk** [comment]
Fails when upgrading from 2023.9 to 2023.10.0b2. I get this error in the logs


```
Logger: homeassistant.setup
Source: setup.py:215 
First occurred: 12:36:01 (1 occurrences) 
Last logged: 12:36:01

Setup failed for custom integration roborock: Unable to import component: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/roborock/__init__.py", line 20, in <module>
    from homeassistant.helpers.integration_platform import (
ImportError: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)
```

**Comment by mesut3000** [comment]
Hi, tried but still the same.

**Comment by wormiedk** [comment]
If I install "main" by using redownload in HACS it works. However it then says there is an update to 1.11. If I install the update the roborock integration fails again in 2023.10.0b3

**Comment by jimz011** [comment]
Well that is because there is no official version yet, you can circumvent this by opening the manifest.json file and change the version number to something higher than the current version.

**Comment by Lash-L** [comment]
Yes an official version will be released on Tuesday night or wednesday morning before the 2023.10 release officially comes out. It is a breaking change, so I don't want to release it too early - as it will break everyones installation who doesn't have 2023.10

**Comment by AseKarlsson** [comment]
Hi,
The HA release 2023.10 is live now.

**Comment by zatricky** [comment]
Same as @KentuckyMC

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 21:32:28 (1 occurrences)
Last logged: 21:32:28

Setup failed for custom integration roborock: Unable to import component: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/roborock/__init__.py", line 20, in <module>
    from homeassistant.helpers.integration_platform import (
ImportError: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)

```

**Comment by FragMenthor** [comment]
Same here: 

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 20:36:22 (1 occurrences)
Last logged: 20:36:22

Setup failed for custom integration roborock: Unable to import component: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/roborock/__init__.py", line 20, in <module>
    from homeassistant.helpers.integration_platform import (
ImportError: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)
```
Re-downloaded the integration, and the same, any solution?

**Comment by arne182** [comment]
Also here.

**Comment by pupe666** [comment]
Dont know if it helps, but I also have the same problem.

`Unable to import component: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)`

**Comment by Lash-L** [comment]
New version is pushed

**Comment by DjBac** [comment]
Wow, that was fast! Seems to be working with 1.0.12

**Comment by Jezza34000** [comment]
Update done, working ok 👍 
Thank you

**Comment by AseKarlsson** [comment]
Working nice, Thanks!

**Comment by Lash-L** [comment]
Perfect! Closing this issue
