### ISSUE TITLE
0.0.9: Unexpected error fetching roborock data

### ISSUE THREAD

**Issue by Boss-man** [humbertogontijo/homeassistant-roborock#61]
After updating to 0.0.9 I get a bunch of these in the log

```
[custom_components.roborock] Unexpected error fetching roborock data: 'int' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/__init__.py", line 80, in _async_update_data
    device_prop = await self.api.get_prop(device_id)
  File "/config/custom_components/roborock/api/api.py", line 320, in get_prop
    if len(clean_summary.records) > 0:
  File "/config/custom_components/roborock/api/containers.py", line 790, in records
    return self.data.get(CleanSummaryField.RECORDS)
AttributeError: 'int' object has no attribute 'get'
2022-12-29 12:40:29.971 ERROR (MainThread) [custom_components.roborock.api.api] Roborock mqtt client disconnected (rc: 7)
```

**Comment by robbinonline** [comment]
I had the same error, then I deleted my credentials and now I can't even setup my vacuum anymore. 

`Error setting up entry Roborock for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 32, in async_setup_entry
    home_data = HomeData(await api_client.get_home_data(user_data))
  File "/config/custom_components/roborock/api/api.py", line 392, in get_home_data
    rriot = user_data.rriot
  File "/config/custom_components/roborock/api/containers.py", line 284, in rriot
    return RRiot(self.data.get(UserDataField.RRIOT))
AttributeError: 'UserData' object has no attribute 'get'`

**Comment by humbertogontijo** [comment]
New release 0.0.10 should fix it

**Comment by Boss-man** [comment]
> New release 0.0.10 should fix it

Just updated, but get new error:

```
2022-12-29 13:25:00.951 ERROR (MainThread) [custom_components.roborock] Unexpected error fetching roborock data: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/__init__.py", line 80, in _async_update_data
    device_prop = await self.api.get_prop(device_id)
  File "/config/custom_components/roborock/api/api.py", line 320, in get_prop
    if len(clean_summary.records) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by humbertogontijo** [comment]
0.0.11 is out ignoring the clean_summary for devices that don't have it

**Comment by Boss-man** [comment]
It works now. But I have a Roborock S6 MaxV and now the current cleaning area is unavailable.

It worked before, but don't know if it will come back when the robot have done a cleaning?

**Comment by Boss-man** [comment]
Just have this error now:
But the integration loads.
```
2022-12-29 14:00:55.473 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up roborock platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/roborock/sensor.py", line 261, in async_setup_entry
    RoborockSensor(
  File "/config/custom_components/roborock/sensor.py", line 283, in __init__
    self._attr_native_value = self._determine_native_value()
  File "/config/custom_components/roborock/sensor.py", line 319, in _determine_native_value
    native_value = getattr(data, self.entity_description.key)
AttributeError: 'CleanSummary' object has no attribute 'begin'
```

**Comment by RamiRihawi** [comment]
> It works now. But I have a Roborock S6 MaxV and now the current cleaning area is unavailable.
> 
> It worked before, but don't know if it will come back when the robot have done a cleaning?

I have the same issue and i can confirm the sensor current cleaning is still unavailable after a cleaning is done

**Comment by Boss-man** [comment]
> I have the same issue and i can confirm the sensor current cleaning is still unavailable after a cleaning is done

I think the sensors are unavailable because of the error I mentioned above. So if that gets fixed the sensors will hopefully come back.

**Comment by Boss-man** [comment]
I just updated to 0.0.14, and now have new sensors.

filter_remaining
main_brush_remaining
sensor_dirty_remaining
side_brush_remaining


Also current_clean_area and current_clean_duration is back and working.


Very good release :)

**Comment by humbertogontijo** [comment]
I'm closing this one to help me keep track of whats failing. Feel free to open a new one if needed
