### ISSUE TITLE
Home Assistant integration fails to start in version 1.0.2

### ISSUE THREAD

**Issue by Alindil** [humbertogontijo/homeassistant-roborock#325]
Since this morning, the integration is not done in Home assistant. I upgraded to version 1.0.2 but it still doesn't launch

![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/30829631/4f0d86bc-9f87-4a0e-b7cd-277e14e845ee)

**Comment by tsrubar** [comment]
+1

**Comment by amcfague** [comment]
Full stack:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/roborock/util.py", line 51, in wrapped
    cache.last_run_result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 364, in get_room_mapping
    mapping = await self.send_command(RoborockCommand.GET_ROOM_MAPPING)
  File "/usr/local/lib/python3.10/site-packages/roborock/local_api.py", line 94, in send_command
    return (await self.send_message(roborock_message))[0]
  File "/usr/local/lib/python3.10/site-packages/roborock/local_api.py", line 137, in send_message
    raise exception
  File "/usr/local/lib/python3.10/site-packages/roborock/local_api.py", line 107, in async_local_response
    (response, err) = await self._async_response(request_id, response_protocol)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 192, in _async_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=76623 Timeout after 4 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/coordinator.py", line 98, in _async_update_data
    await self.fill_device_info(self.device_info)
  File "/config/custom_components/roborock/coordinator.py", line 87, in fill_device_info
    await asyncio.gather(
  File "/config/custom_components/roborock/coordinator.py", line 63, in fill_room_mapping
    room_mapping = await self.api.get_room_mapping()
  File "/usr/local/lib/python3.10/site-packages/roborock/util.py", line 56, in wrapped
    cache.last_run_result.is_cached = True
AttributeError: 'list' object has no attribute 'is_cached'
```

**Comment by Boss-man** [comment]
What version of Home Assistant ? I'm still on 2023.4.6 and 1.02 starts fine here.

**Comment by xtrmenl** [comment]
i'm running Home Assistant 2023.5.3 in which it doesnt work (1.02)
fallback to 1.01 makes it work again

**Comment by darkkatarsis** [comment]
Try to remove and re-add device to integration.

**Comment by xtrmenl** [comment]
for me it is working again 
what i did 
remove device, remove integration, delete hacs via UI, reboot HA, instal integration via hacs, add intergation, login -> works (again) with all "old" entities incl map etc

**Comment by Trilis29** [comment]
Same for me

**Comment by inertia666** [comment]
This broke for me a few days ago. Now even with the latest 1.0.6 I cannot get the Roborock to be found. Have tried uninstall, reinstall several times.

HA 2023.5.4

**Comment by AseKarlsson** [comment]
Same issue here after upgrading from 1.0.6 to 1.0.7.
Others with same issue?

**Comment by Lash-L** [comment]
Anyone still having issues on 1.0.11?
