### ISSUE TITLE
Cannot Set Up New Vacuum - Failed to get data the first time

### ISSUE THREAD

**Issue by ccigas** [humbertogontijo/homeassistant-roborock#677]
## What vacuum are you using?
QRevo Master

## Describe the bug

Attempting to reload the integration to grab the newly setup vacuuming errors with 'int' object has no attribute 'name'

## Debug log

```

"Not setting up *vacuum* because the coordinator failed to get data for the first time using the offline client Please create an issue with the following error included: 'int' object has no attribute 'name'

```

**Comment by Tiemichael** [comment]
Same here, with Roborock S6
Version:	core-2024.12.5
Installation type:	Home Assistant OS

All I see is:
Failed Setup, will retry: there are no devices that con currently be reached. ( PING to Roborock is working)

And a warning in the log: 
`INFO (MainThread) [homeassistant.setup] Setting up roborock
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'roborock' sets option flow config_entry explicitly, which is deprecated at custom_components/roborock/config_flow.py, line 322: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/humbertogontijo/homeassistant-roborock/issues
`
