### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by lovelyelfpop** [humbertogontijo/homeassistant-roborock#715]
Roborock 1.0.16
Core 2025.7.1
Supervisor 2025.07.1
Operating System 16.0
Frontend 20250702.1

```
2025-07-13 20:25:33.498 ERROR (MainThread) [roborock.version_1_apis.roborock_local_client_v1] [扫地机器人] id=1 Timeout after 4 seconds
2025-07-13 20:25:33.499 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxx@qq.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 142, in async_setup_entry
    _coordinator.release()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/roborock/coordinator.py", line 57, in release
    self.api.sync_disconnect()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RoborockLocalClientV1' object has no attribute 'sync_disconnect'. Did you mean: 'async_disconnect'?
2025-07-13 20:25:41.093 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setups for integration xiaomi_cloud with title: 10xxx85 and entry_id: 01JAVxxxxxxxxxxxxxxxCWJW2N, during setup without awaiting async_forward_entry_setups, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2586, in async_forward_entry_setups
    _report_non_awaited_platform_forwards(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1337, in _report_non_awaited_platform_forwards
    report_usage(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 204, in report_usage
    _report_usage_partial()
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 243, in _report_usage
    _report_usage_no_integration(what, core_behavior, breaks_in_ha_version, err)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 380, in _report_usage_no_integration
    _LOGGER.warning(msg, stack_info=True)
2025-07-13 20:25:57.665 ERROR (MainThread) [homeassistant.core] Error running job: <Job onetime listen homeassistant_start <function _async_at_core_state.<locals>._matched_event at 0x7fe0ff4707c0> HassJobType.Callback <_OneTimeListener homeassistant.helpers.start:<function _async_at_core_state.<locals>._matched_event at 0x7fe0ff4707c0>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 661, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    numerical_value = float(value)
ValueError: could not convert string to float: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1573, in async_fire_internal
    self._hass.async_run_hass_job(job, event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 935, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1434, in __call__
    self.hass.async_run_hass_job(self.listener_job, event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 935, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/start.py", line 44, in _matched_event
    hass.async_run_hass_job(at_start_job, hass)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 935, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 539, in _async_template_startup
    result_info.async_refresh()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1132, in async_refresh
    self._refresh(None)
    ~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1318, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 935, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 485, in _handle_results
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1018, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1140, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1080, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1024, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 668, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
```

**Comment by JimRnewell** [comment]
same issue here

**Comment by JimRnewell** [comment]
have gone into roborock and then settings, under roborock checked the box, use cloud integration, now works again

**Comment by EWK1** [comment]
> have gone into roborock and then settings, under roborock checked the box, use cloud integration, now works again

In the app, website or in home assistant?
