### ISSUE TITLE
Roborock Q8 Max - Invalid config, Hubs Not loaded

### ISSUE THREAD

**Issue by ciechomir** [humbertogontijo/homeassistant-roborock#497]
Edit: working with 1.0.12 - update by HACS

1. Can't delete integration 
2. Can't add new HUB - with:
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

Logs:

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 4 października 2023 21:38:36 (1 occurrences)
Last logged: 4 października 2023 21:38:36

Setup failed for custom integration roborock: Unable to import component: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/roborock/__init__.py", line 20, in <module>
    from homeassistant.helpers.integration_platform import (
ImportError: cannot import name 'async_process_integration_platform_for_component' from 'homeassistant.helpers.integration_platform' (/usr/src/homeassistant/homeassistant/helpers/integration_platform.py)

**Comment by trendelkamp** [comment]
same here

**Comment by hostrup** [comment]
Hi! I have the same problem. 
Mine is a Q7 Max.

**Comment by lindstrm** [comment]
Same here on HA 2023.10.0.

**Comment by foekpham** [comment]
I had the same problem.
Update Roborock integration via HACS to 1.0.12 works for me aswell
